# Sample .travis.yml for R projects.
# Taken from my fork of Craig Citro's r-travis
#
# See https://github.com/eddelbuettel/r-travis/
# and https://github.com/craigcitro/r-travis
#
# See README.md for instructions.

language: c

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - curl -OL https://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - sha256sum travis-tool.sh | grep -q 0aa65b33dd4f6b5280b80e2ed9d7f8738a753d7f59ca6066cc900696971b5571
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  ## -- nothing to do here
  ## - ./travis-tool.sh install_r 

script: ./travis-tool.sh run_tests

notifications:
  email:
    on_success: change
    on_failure: change

